# Generated by Django 4.2.5 on 2024-06-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_users_date_joined_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_joined',
            field=models.DateTimeField(default='2024-06-06T16:06:16.532032+07:00', verbose_name='date joined'),
        ),
    ]
