# Generated by Django 4.2.5 on 2024-06-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_users_date_joined_delete_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_joined',
            field=models.DateTimeField(default='2024-06-06T18:48:10.082178+07:00', verbose_name='date joined'),
        ),
    ]
