# Generated by Django 4.2.5 on 2024-06-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_users_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_joined',
            field=models.DateTimeField(default='2024-06-12T00:10:41.074155+07:00', verbose_name='date joined'),
        ),
    ]
