# Generated by Django 4.2.5 on 2024-06-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_code_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listfeatures',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
